### ISSUE TITLE
Design KiCad project file scrubber

### ISSUE THREAD

**Issue by jaylamb** [apcountryman/prototype-kicad-library-ci#12]
**Feature Design**

- [ ] Add a Git config install script to remove the information from the `last_client` and `update` lines from any KiCad `.pro` files within the repository.
- [ ] Add a CI script which will ensure that there is no information in the `last_client` or `update` fields of any of the repository's `.pro` files.

Once the install script is run, the targeted lines should read:

`update=`

`last_client=`

... and the CI script will ensure that they do.

**Feature use case**

Scripts will provide for the automated removal of uneccessary information from any KiCad project files, and ensure the removal prior to any merge.

**Description of behavior**

* `git/config/install`: Runs automatically during the commit process, and will remove the desired information from the targeted files (see above).
* `ci/scrub-kicad-project-files`: Part of the project's CI checks, this script ensures the desired information has been removed from the targeted files.

**Detailed Design**

* `git/config/install`: This file will be a complete Bash script (with error reporting, help text, and version information). The primary function of the script will be a pair of calls to the `sed` command:

```
if ! git -C "$repository" config --local filter.kicad_project.clean "sed -E -e 's/^update=.*$/update=/' -e 's/^last_client=.*$/last_client=/'" > "/dev/null"; then
    abort "KiCad project filter clean command installation failure"
fi

if ! git -C "$repository" config --local filter.kicad_project.smudge "cat" > "/dev/null"; then
    abort "KiCad project filter smudge command installation failure"
fi
```

* `ci/scrub-kicad-project-files`: This file will be a complete Bash script (with error reporting, help text, and version information). The primary function of the script will use similar calls to sed, followed by a check to ensure the calls did not result in a change to the KiCad project file(s):

```
if ! ( cd "$repository" && sed -E -e 's/^update=.*$/update=/' -e 's/^last_client=.*$/last_client=/' && git -C "$repository" diff --exit-code ); then
    abort
fi
```

**Comment by apcountryman** [comment]
There seems to be a slight misunderstanding or misstatement of what the proposed `git/config/install` script does. This script is not run automatically during the commit process. Instead, it is run once after cloning the repository to "install" the KiCad project file filter's clean command (the `sed` invocation) and smudge command (the `cat` invocation) by creating a `kicad_project` filter entry in the repository's `.git/config` file. The filter's clean command is run automatically during the commit process. The filter's smudge command, which does nothing in this case, is run automatically during the checkout process. An entry (`*.pro filter=kicad_project`) will need to be added to the repository's Git attributes file (`.gitattributes`) to control which files the filter is applied to.

The `ci/scrub-kicad-project-files` script will need to create a list of KiCad project files and pass them to the `sed` invocation:
```bash
local kicad_project_files; mapfile -t kicad_project_files < <( git -C "$repository" ls-files '*.pro' | xargs -r -d '\n' -I '{}' find "$repository/{}" ); readonly kicad_project_files

if ! ( sed -E -e 's/^update=.*$/update=/' -e 's/^last_client=.*$/last_client=/' "${kicad_project_files[@]}" && git -C "$repository" diff --exit-code ); then
    abort
fi
```

Other than those, this design LGTM. I'll open a `type-feature` issue for implementing this new feature shortly.
