### ISSUE TITLE
Transition to KiCad 6

### ISSUE THREAD

**Issue by apcountryman** [apcountryman/prototype-kicad-library-ci#27]
Transition to KiCad 6.
- [ ] Update official libraries and utilities submodules to track the `master` branch instead of the `v5` branch
    - [ ] `official-libraries/kicad-symbols`
    - [ ] `official-libraries/kicad-footprints`
    - [ ] `utilities/kicad-library-utils`
- [ ] Update `check-klc-compliance` CI script symbol library identification rules (`*.lib` -> `.kicad_sym`): https://github.com/apcountryman/prototype-kicad-library-ci/blob/e87c0822ec90e63fefd866abd258669db11a1e42/ci/check-klc-compliance#L56
- [ ] Update test library/project KiCad files
    - [ ] `fp-lib-table`
    - [ ] `sym-lib-table`
    - [ ] `test.dcm`
    - [ ] `test.lib` -> `test.kicad_sym`
    - [ ] `test.pretty/10_uMAX.kicad_mod`
    - [ ] `test.pro`

**Comment by apcountryman** [comment]
KiCad 6 transition issue has been opened @jaylamb

**Comment by jaylamb** [comment]
The `scrub-kicad-project-files` script searches for `.pro` files within the target repository and removes the entries in the `update=` and `last_client=` fields.

KiCad 6 uses a `.kicad_prl` and `.kicad_pro` file in lieu of the `.pro` file, neither of which appears to use the fields, or similar ones which would require a scrub. Looking for a recommendation on moving forward with the `scrub-kicad-project-files` script, though it appears it may not be necessary at this point.

**Comment by apcountryman** [comment]
> The `scrub-kicad-project-files` script searches for `.pro` files within the target repository and removes the entries in the `update=` and `last_client=` fields.
> 
> KiCad 6 uses a `.kicad_prl` and `.kicad_pro` file in lieu of the `.pro` file, neither of which appears to use the fields, or similar ones which would require a scrub. Looking for a recommendation on moving forward with the `scrub-kicad-project-files` script, though it appears it may not be necessary at this point.

I agree with your assessment that the scrub script (and associated CI workflow) are no longer necessary and thus they can be removed.
